# Generated by Django 4.1.7 on 2023-04-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_lessons_status_alter_lessons_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='status',
            field=models.CharField(choices=[('paye7_season1', 'paye7_season1'), ('paye7_season2', 'paye7_season2'), ('paye7_season3', 'paye7_season3'), ('paye7_season4', 'paye7_season4'), ('paye7_season5', 'paye7_season5'), ('paye7_season6', 'paye7_season6'), ('paye7_season7', 'paye7_season7'), ('paye7_season8', 'paye7_season8'), ('paye7_season9', 'paye7_season9'), ('paye8_season1', 'paye8_season1'), ('paye8_season2', 'paye8_season2'), ('paye8_season3', 'paye8_season3'), ('paye8_season4', 'paye8_season4'), ('paye8_season5', 'paye8_season5'), ('paye8_season6', 'paye8_season6'), ('paye8_season7', 'paye8_season7'), ('paye8_season8', 'paye8_season8'), ('paye8_season9', 'paye8_season9'), ('paye9_season1', 'paye9_season1'), ('paye9_season2', 'paye9_season2'), ('paye9_season3', 'paye9_season3'), ('paye9_season4', 'paye9_season4'), ('paye9_season5', 'paye9_season5'), ('paye9_season6', 'paye9_season6'), ('paye9_season7', 'paye9_season7'), ('paye9_season8', 'paye9_season8')], max_length=50),
        ),
    ]
